/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Algoritmos;

import static Algoritmos.Algoritmos.avaliaSolucao;
import java.util.ArrayList;
import java.util.HashSet;

import java.util.List;
import java.util.Set;
import java.util.Map;



import representacao.Request;
import representacao.Rota;
import representacao.Solucao;

/**
 *
 * @author Renan
 */
public class Inicializacao {
 
     
    public static void CarregaSolucao(List<Solucao> Pop,List<Request> listRequests, Map<Integer, List<Request>> Pin,
                                      Map<Integer, List<Request>> Pout, Integer n, Integer Qmax, Set<Integer> K, List<Request> U, List<Request> P,
                                      List<Integer> m, List<List<Integer>> d, List<List<Integer>> c, Integer TimeWindows, Integer currentTime, Integer lastNode) {
        Solucao S = new Solucao();
        List<Integer> individuo = new ArrayList<>();
        
        individuo.add(7);
        individuo.add(2);
        individuo.add(3);
        individuo.add(2);
        individuo.add(6);
        individuo.add(9);
        individuo.add(4);
        individuo.add(8);
        individuo.add(9);
        individuo.add(3);
        individuo.add(4);
        individuo.add(5);
        individuo.add(10);
        individuo.add(8);
        individuo.add(3);
        individuo.add(7);
        individuo.add(1);
        individuo.add(1);
        individuo.add(5);
        individuo.add(3);
        individuo.add(10);
        individuo.add(6);
        individuo.add(3);
        individuo.add(2);
        individuo.add(10);
        individuo.add(7);
        individuo.add(6);
        individuo.add(1);
        individuo.add(9);
        individuo.add(3);
        individuo.add(1);
        individuo.add(3);
        individuo.add(1);
        individuo.add(2);
        individuo.add(9);
        individuo.add(8);
        individuo.add(4);
        individuo.add(5);
        individuo.add(10);
        individuo.add(2);
        individuo.add(3);
        individuo.add(1);
        individuo.add(6);
        individuo.add(5);
        //System.out.println("Individuo = " + individuo);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(0).setSolucao(S);
        //System.out.println(Pop.get(0));
        individuo.clear();

        
        individuo.add(3);
        individuo.add(2);
        individuo.add(6);
        individuo.add(9);
        individuo.add(4);
        individuo.add(8);
        individuo.add(1);
        individuo.add(5);
        individuo.add(3);
        individuo.add(10);
        individuo.add(4);
        individuo.add(1);
        individuo.add(7);
        individuo.add(9);
        individuo.add(8);
        individuo.add(3);
        individuo.add(6);
        individuo.add(8);
        individuo.add(9);
        individuo.add(10);
        individuo.add(5);
        individuo.add(7);
        individuo.add(10);
        individuo.add(1);
        individuo.add(7);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        individuo.add(1);
        individuo.add(3);
        individuo.add(2);
        individuo.add(8);
        individuo.add(5);
        individuo.add(1);
        individuo.add(6);
        individuo.add(5);
        individuo.add(1);
        individuo.add(7);
        individuo.add(2);
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(1).setSolucao(S);
        individuo.clear();

        individuo.add(1);
        individuo.add(3);
        individuo.add(2);
        individuo.add(8);
        individuo.add(9);
        individuo.add(5);
        individuo.add(2);
        individuo.add(6);
        individuo.add(8);
        individuo.add(6);
        individuo.add(9);
        individuo.add(1);
        individuo.add(10);
        individuo.add(11);
        individuo.add(8);
        individuo.add(10);
        individuo.add(7);
        individuo.add(3);
        individuo.add(4);
        individuo.add(5);
        individuo.add(7);
        individuo.add(10);
        individuo.add(1);
        individuo.add(1);
        individuo.add(3);
        individuo.add(8);
        individuo.add(5);
        individuo.add(1);
        individuo.add(4);
        individuo.add(10);
        individuo.add(3);
        individuo.add(6);
        individuo.add(10);
        individuo.add(6);
        individuo.add(8);
        individuo.add(9);
        individuo.add(4);
        individuo.add(10);
        individuo.add(7);
        individuo.add(3);
        individuo.add(1);
        individuo.add(6);
        individuo.add(5);
        individuo.add(8);
        individuo.add(7);
        individuo.add(2);
        individuo.add(1);
        individuo.add(2);
        individuo.add(6);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(2).setSolucao(S);
        individuo.clear();

        individuo.add(8);
        individuo.add(1);
        individuo.add(7);
        individuo.add(8);
        individuo.add(2);
        individuo.add(1);
        individuo.add(2);
        individuo.add(5);
        individuo.add(10);
        individuo.add(11);
        individuo.add(3);
        individuo.add(10);
        individuo.add(7);
        individuo.add(3);
        individuo.add(1);
        individuo.add(10);
        individuo.add(6);
        individuo.add(9);
        individuo.add(4);
        individuo.add(2);
        individuo.add(3);
        individuo.add(9);
        individuo.add(4);
        individuo.add(1);
        individuo.add(3);
        individuo.add(1);
        individuo.add(2);
        individuo.add(5);
        individuo.add(6);
        individuo.add(8);
        individuo.add(2);
        individuo.add(7);
        individuo.add(9);
        individuo.add(3);
        individuo.add(8);
        individuo.add(2);
        individuo.add(5);
        individuo.add(2);
        individuo.add(5);
        individuo.add(2);
        individuo.add(5);
        individuo.add(7);
        individuo.add(1);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(3).setSolucao(S);
        individuo.clear();
        
        individuo.add(1);
        individuo.add(5);
        individuo.add(2);
        individuo.add(9);
        individuo.add(3);
        individuo.add(2);
        individuo.add(7);
        individuo.add(1);
        individuo.add(5);
        individuo.add(3);
        individuo.add(9);
        individuo.add(11);
        individuo.add(6);
        individuo.add(9);
        individuo.add(10);
        individuo.add(2);
        individuo.add(10);
        individuo.add(7);
        individuo.add(3);
        individuo.add(6);
        individuo.add(10);
        individuo.add(8);
        individuo.add(9);
        individuo.add(6);
        individuo.add(10);
        individuo.add(9);
        individuo.add(6);
        individuo.add(7);
        individuo.add(10);
        individuo.add(8);
        individuo.add(4);
        individuo.add(3);
        individuo.add(1);
        individuo.add(2);
        individuo.add(5);
        individuo.add(9);
        individuo.add(10);
        individuo.add(3);
        individuo.add(4);
        individuo.add(3);
        individuo.add(1);
        individuo.add(8);
        individuo.add(6);
        individuo.add(1);
        individuo.add(4);
        individuo.add(7);
        individuo.add(8);
        individuo.add(1);
        individuo.add(2);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(4).setSolucao(S);
        individuo.clear();
        
        individuo.add(5);
        individuo.add(9);
        individuo.add(10);
        individuo.add(3);
        individuo.add(4);
        individuo.add(3);
        individuo.add(5);
        individuo.add(10);
        individuo.add(4);
        individuo.add(7);
        individuo.add(1);
        individuo.add(6);
        individuo.add(9);
        individuo.add(11);
        individuo.add(1);
        individuo.add(10);
        individuo.add(6);
        individuo.add(1);
        individuo.add(5);
        individuo.add(4);
        individuo.add(1);
        individuo.add(5);
        individuo.add(2);
        individuo.add(9);
        individuo.add(3);
        individuo.add(6);
        individuo.add(2);
        individuo.add(6);
        individuo.add(4);
        individuo.add(6);
        individuo.add(8);
        individuo.add(2);
        individuo.add(5);
        individuo.add(1);
        individuo.add(8);
        individuo.add(6);
        individuo.add(10);
        individuo.add(8);
        individuo.add(1);
        individuo.add(11);
        individuo.add(6);
        individuo.add(7);
        individuo.add(10);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(5).setSolucao(S);
        individuo.clear();
        
        individuo.add(2);
        individuo.add(1);
        individuo.add(5);
        individuo.add(2);
        individuo.add(5);
        individuo.add(2);
        individuo.add(7);
        individuo.add(8);
        individuo.add(10);
        individuo.add(1);
        individuo.add(10);
        individuo.add(11);
        individuo.add(6);
        individuo.add(9);
        individuo.add(3);
        individuo.add(5);
        individuo.add(4);
        individuo.add(5);
        individuo.add(1);
        individuo.add(10);
        individuo.add(8);
        individuo.add(6);
        individuo.add(10);
        individuo.add(7);
        individuo.add(5);
        individuo.add(9);
        individuo.add(10);
        individuo.add(9);
        individuo.add(2);
        individuo.add(8);
        individuo.add(6);
        individuo.add(3);
        individuo.add(10);
        individuo.add(4);
        individuo.add(4);
        individuo.add(7);
        individuo.add(10);
        individuo.add(3);
        individuo.add(6);
        individuo.add(3);
        individuo.add(4);
        individuo.add(1);
        individuo.add(6);
        individuo.add(8);
        individuo.add(1);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(6).setSolucao(S);
        individuo.clear();
        
        individuo.add(1);
        individuo.add(3);
        individuo.add(2);
        individuo.add(1);
        individuo.add(5);
        individuo.add(2);
        individuo.add(8);
        individuo.add(5);
        individuo.add(7);
        individuo.add(10);
        individuo.add(1);
        individuo.add(7);
        individuo.add(10);
        individuo.add(2);
        individuo.add(6);
        individuo.add(7);
        individuo.add(8);
        individuo.add(2);
        individuo.add(1);
        individuo.add(9);
        individuo.add(4);
        individuo.add(2);
        individuo.add(3);
        individuo.add(8);
        individuo.add(9);
        individuo.add(1);
        individuo.add(5);
        individuo.add(9);
        individuo.add(6);
        individuo.add(8);
        individuo.add(9);
        individuo.add(10);
        individuo.add(2);
        individuo.add(5);
        individuo.add(1);
        individuo.add(8);
        individuo.add(6);
        individuo.add(10);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(7).setSolucao(S);
        individuo.clear();
        
        individuo.add(4);
        individuo.add(7);
        individuo.add(5);
        individuo.add(3);
        individuo.add(1);
        individuo.add(6);
        individuo.add(10);
        individuo.add(5);
        individuo.add(9);
        individuo.add(10);
        individuo.add(3);
        individuo.add(5);
        individuo.add(9);
        individuo.add(6);
        individuo.add(9);
        individuo.add(8);
        individuo.add(10);
        individuo.add(2);
        individuo.add(8);
        individuo.add(1);
        individuo.add(9);
        individuo.add(10);
        individuo.add(2);
        individuo.add(8);
        individuo.add(4);
        individuo.add(3);
        individuo.add(5);
        individuo.add(10);
        individuo.add(7);
        individuo.add(9);
        individuo.add(4);
        individuo.add(1);
        individuo.add(1);
        individuo.add(3);
        individuo.add(8);
        individuo.add(5);
        individuo.add(9);
        individuo.add(1);
        individuo.add(10);
        individuo.add(2);
        individuo.add(11);
        individuo.add(1);
        individuo.add(6);
        individuo.add(5);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(8).setSolucao(S);
        individuo.clear();
        
        individuo.add(8);
        individuo.add(1);
        individuo.add(8);
        individuo.add(1);
        individuo.add(5);
        individuo.add(7);
        individuo.add(8);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        individuo.add(1);
        individuo.add(3);
        individuo.add(5);
        individuo.add(9);
        individuo.add(10);
        individuo.add(9);
        individuo.add(4);
        individuo.add(3);
        individuo.add(6);
        individuo.add(2);
        individuo.add(4);
        individuo.add(6);
        individuo.add(9);
        individuo.add(10);
        individuo.add(9);
        individuo.add(5);
        individuo.add(11);
        individuo.add(10);
        individuo.add(1);
        individuo.add(7);
        individuo.add(8);
        individuo.add(6);
        individuo.add(1);
        individuo.add(2);
        individuo.add(8);
        individuo.add(3);
        individuo.add(10);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(9).setSolucao(S);
        individuo.clear();
        
        individuo.add(3);
        individuo.add(10);
        individuo.add(1);
        individuo.add(5);
        individuo.add(1);
        individuo.add(2);
        individuo.add(8);
        individuo.add(9);
        individuo.add(4);
        individuo.add(3);
        individuo.add(4);
        individuo.add(10);
        individuo.add(1);
        individuo.add(8);
        individuo.add(1);
        individuo.add(9);
        individuo.add(7);
        individuo.add(2);
        individuo.add(11);
        individuo.add(6);
        individuo.add(10);
        individuo.add(11);
        individuo.add(7);
        individuo.add(10);
        individuo.add(3);
        individuo.add(2);
        individuo.add(9);
        individuo.add(6);
        individuo.add(7);
        individuo.add(2);
        individuo.add(5);
        individuo.add(1);
        individuo.add(6);
        individuo.add(4);
        individuo.add(10);
        individuo.add(6);
        individuo.add(8);
        individuo.add(3);
        individuo.add(4);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(10).setSolucao(S);
        individuo.clear();
        
        individuo.add(8);
        individuo.add(1);
        individuo.add(1);
        individuo.add(5);
        individuo.add(3);
        individuo.add(8);
        individuo.add(9);
        individuo.add(6);
        individuo.add(4);
        individuo.add(3);
        individuo.add(6);
        individuo.add(2);
        individuo.add(4);
        individuo.add(6);
        individuo.add(5);
        individuo.add(9);
        individuo.add(10);
        individuo.add(6);
        individuo.add(3);
        individuo.add(10);
        individuo.add(6);
        individuo.add(4);
        individuo.add(6);
        individuo.add(10);
        individuo.add(3);
        individuo.add(6);
        individuo.add(5);
        individuo.add(9);
        individuo.add(1);
        individuo.add(5);
        individuo.add(4);
        individuo.add(8);
        individuo.add(1);
        individuo.add(11);
        individuo.add(4);
        individuo.add(3);
        individuo.add(4);
        individuo.add(6);
        individuo.add(1);
        individuo.add(3);
        individuo.add(10);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(11).setSolucao(S);
        individuo.clear();
        
        individuo.add(6);
        individuo.add(8);
        individuo.add(4);
        individuo.add(7);
        individuo.add(3);
        individuo.add(6);
        individuo.add(10);
        individuo.add(1);
        individuo.add(3);
        individuo.add(4);
        individuo.add(6);
        individuo.add(1);
        individuo.add(1);
        individuo.add(3);
        individuo.add(5);
        individuo.add(9);
        individuo.add(10);
        individuo.add(6);
        individuo.add(2);
        individuo.add(7);
        individuo.add(8);
        individuo.add(1);
        individuo.add(9);
        individuo.add(3);
        individuo.add(10);
        individuo.add(10);
        individuo.add(2);
        individuo.add(10);
        individuo.add(8);
        individuo.add(9);
        individuo.add(7);
        individuo.add(2);
        individuo.add(11);
        individuo.add(6);
        individuo.add(10);
        individuo.add(3);
        individuo.add(6);
        individuo.add(10);
        individuo.add(1);
        individuo.add(4);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(12).setSolucao(S);
        individuo.clear();
        
        individuo.add(7);
        individuo.add(8);
        individuo.add(1);
        individuo.add(10);
        individuo.add(1);
        individuo.add(2);
        individuo.add(1);
        individuo.add(5);
        individuo.add(3);
        individuo.add(4);
        individuo.add(3);
        individuo.add(6);
        individuo.add(1);
        individuo.add(4);
        individuo.add(1);
        individuo.add(3);
        individuo.add(8);
        individuo.add(5);
        individuo.add(1);
        individuo.add(7);
        individuo.add(5);
        individuo.add(10);
        individuo.add(6);
        individuo.add(10);
        individuo.add(1);
        individuo.add(9);
        individuo.add(2);
        individuo.add(6);
        individuo.add(2);
        individuo.add(4);
        individuo.add(6);
        individuo.add(2);
        individuo.add(1);
        individuo.add(8);
        individuo.add(5);
        individuo.add(7);
        individuo.add(1);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(13).setSolucao(S);
        individuo.clear();
        
        individuo.add(10);
        individuo.add(11);
        individuo.add(8);
        individuo.add(6);
        individuo.add(8);
        individuo.add(4);
        individuo.add(10);
        individuo.add(6);
        individuo.add(1);
        individuo.add(7);
        individuo.add(4);
        individuo.add(3);
        individuo.add(5);
        individuo.add(1);
        individuo.add(5);
        individuo.add(3);
        individuo.add(10);
        individuo.add(3);
        individuo.add(4);
        individuo.add(1);
        individuo.add(7);
        individuo.add(6);
        individuo.add(3);
        individuo.add(1);
        individuo.add(6);
        individuo.add(1);
        individuo.add(2);
        individuo.add(5);
        individuo.add(9);
        individuo.add(1);
        individuo.add(4);
        individuo.add(8);
        individuo.add(5);
        individuo.add(9);
        individuo.add(6);
        individuo.add(2);
        individuo.add(9);
        individuo.add(10);
        individuo.add(8);
        individuo.add(1);
        individuo.add(3);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(14).setSolucao(S);
        individuo.clear();
        
        individuo.add(4);
        individuo.add(2);
        individuo.add(3);
        individuo.add(9);
        individuo.add(8);
        individuo.add(4);
        individuo.add(1);
        individuo.add(1);
        individuo.add(3);
        individuo.add(1);
        individuo.add(2);
        individuo.add(5);
        individuo.add(6);
        individuo.add(8);
        individuo.add(9);
        individuo.add(3);
        individuo.add(10);
        individuo.add(3);
        individuo.add(10);
        individuo.add(4);
        individuo.add(8);
        individuo.add(1);
        individuo.add(11);
        individuo.add(8);
        individuo.add(6);
        individuo.add(1);
        individuo.add(10);
        individuo.add(8);
        individuo.add(3);
        individuo.add(1);
        individuo.add(11);
        individuo.add(7);
        individuo.add(10);
        individuo.add(3);
        individuo.add(6);
        individuo.add(7);
        individuo.add(4);
        individuo.add(6);
        individuo.add(1);
        individuo.add(9);
        individuo.add(6);
        individuo.add(2);
        individuo.add(10);
        individuo.add(6);
        individuo.add(1);
        individuo.add(5);
        individuo.add(4);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(15).setSolucao(S);
        individuo.clear();
        
        individuo.add(6);
        individuo.add(5);
        individuo.add(2);
        individuo.add(10);
        individuo.add(6);
        individuo.add(7);
        individuo.add(4);
        individuo.add(1);
        individuo.add(8);
        individuo.add(1);
        individuo.add(3);
        individuo.add(1);
        individuo.add(2);
        individuo.add(8);
        individuo.add(3);
        individuo.add(9);
        individuo.add(5);
        individuo.add(6);
        individuo.add(1);
        individuo.add(8);
        individuo.add(1);
        individuo.add(5);
        individuo.add(1);
        individuo.add(3);
        individuo.add(4);
        individuo.add(10);
        individuo.add(1);
        individuo.add(6);
        individuo.add(9);
        individuo.add(4);
        individuo.add(10);
        individuo.add(2);
        individuo.add(1);
        individuo.add(6);
        individuo.add(8);
        individuo.add(11);
        individuo.add(7);
        individuo.add(11);
        individuo.add(9);
        individuo.add(5);
        individuo.add(6);
        individuo.add(4);
        individuo.add(7);
        individuo.add(8);
        individuo.add(3);
        individuo.add(11);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(16).setSolucao(S);
        individuo.clear();
        
        individuo.add(1);
        individuo.add(5);
        individuo.add(2);
        individuo.add(9);
        individuo.add(4);
        individuo.add(3);
        individuo.add(6);
        individuo.add(10);
        individuo.add(4);
        individuo.add(1);
        individuo.add(2);
        individuo.add(6);
        individuo.add(2);
        individuo.add(8);
        individuo.add(3);
        individuo.add(10);
        individuo.add(1);
        individuo.add(10);
        individuo.add(11);
        individuo.add(8);
        individuo.add(7);
        individuo.add(6);
        individuo.add(8);
        individuo.add(6);
        individuo.add(2);
        individuo.add(7);
        individuo.add(9);
        individuo.add(8);
        individuo.add(10);
        individuo.add(3);
        individuo.add(8);
        individuo.add(1);
        individuo.add(5);
        individuo.add(1);
        individuo.add(3);
        individuo.add(4);
        individuo.add(7);
        individuo.add(2);
        individuo.add(1);
        individuo.add(5);
        individuo.add(11);
        individuo.add(9);
        individuo.add(8);
        individuo.add(7);
        individuo.add(5);
        individuo.add(11);
        individuo.add(6);
        individuo.add(1);
        individuo.add(2);
        individuo.add(7);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(17).setSolucao(S);
        individuo.clear();
        
        individuo.add(2);
        individuo.add(1);
        individuo.add(5);
        individuo.add(8);
        individuo.add(6);
        individuo.add(5);
        individuo.add(8);
        individuo.add(1);
        individuo.add(2);
        individuo.add(6);
        individuo.add(7);
        individuo.add(6);
        individuo.add(1);
        individuo.add(10);
        individuo.add(9);
        individuo.add(10);
        individuo.add(3);
        individuo.add(4);
        individuo.add(5);
        individuo.add(6);
        individuo.add(10);
        individuo.add(2);
        individuo.add(1);
        individuo.add(7);
        individuo.add(4);
        individuo.add(10);
        individuo.add(2);
        individuo.add(6);
        individuo.add(9);
        individuo.add(11);
        individuo.add(1);
        individuo.add(5);
        individuo.add(8);
        individuo.add(9);
        individuo.add(1);
        individuo.add(5);
        individuo.add(4);
        individuo.add(9);
        individuo.add(10);
        individuo.add(2);
        individuo.add(10);
        individuo.add(8);
        individuo.add(3);
        individuo.add(10);
        individuo.add(6);
        individuo.add(4);
        individuo.add(2);
        individuo.add(9);
        individuo.add(6);
        individuo.add(4);
        individuo.add(3);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(18).setSolucao(S);
        individuo.clear();
        
        individuo.add(10);
        individuo.add(2);
        individuo.add(6);
        individuo.add(5);
        individuo.add(7);
        individuo.add(8);
        individuo.add(2);
        individuo.add(9);
        individuo.add(1);
        individuo.add(4);
        individuo.add(3);
        individuo.add(6);
        individuo.add(2);
        individuo.add(6);
        individuo.add(4);
        individuo.add(1);
        individuo.add(3);
        individuo.add(2);
        individuo.add(1);
        individuo.add(5);
        individuo.add(9);
        individuo.add(6);
        individuo.add(8);
        individuo.add(2);
        individuo.add(10);
        individuo.add(1);
        individuo.add(6);
        individuo.add(9);
        individuo.add(2);
        individuo.add(8);
        individuo.add(10);
        individuo.add(6);
        individuo.add(10);
        individuo.add(11);
        individuo.add(7);
        individuo.add(10);
        individuo.add(7);
        individuo.add(9);
        individuo.add(8);
        individuo.add(11);
        individuo.add(10);
        individuo.add(1);
        individuo.add(6);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(19).setSolucao(S);
        individuo.clear();
        
        individuo.add(2);
        individuo.add(1);
        individuo.add(8);
        individuo.add(5);
        individuo.add(1);
        individuo.add(2);
        individuo.add(7);
        individuo.add(9);
        individuo.add(8);
        individuo.add(6);
        individuo.add(4);
        individuo.add(1);
        individuo.add(8);
        individuo.add(1);
        individuo.add(6);
        individuo.add(8);
        individuo.add(4);
        individuo.add(3);
        individuo.add(8);
        individuo.add(10);
        individuo.add(1);
        individuo.add(7);
        individuo.add(10);
        individuo.add(3);
        individuo.add(6);
        individuo.add(10);
        individuo.add(4);
        individuo.add(3);
        individuo.add(6);
        individuo.add(10);
        individuo.add(1);
        individuo.add(4);
        individuo.add(8);
        individuo.add(1);
        individuo.add(9);
        individuo.add(7);
        individuo.add(11);
        individuo.add(10);
        individuo.add(2);
        individuo.add(6);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(20).setSolucao(S);
        individuo.clear();
        
        individuo.add(5);
        individuo.add(9);
        individuo.add(6);
        individuo.add(8);
        individuo.add(2);
        individuo.add(10);
        individuo.add(6);
        individuo.add(1);
        individuo.add(5);
        individuo.add(8);
        individuo.add(4);
        individuo.add(5);
        individuo.add(9);
        individuo.add(10);
        individuo.add(9);
        individuo.add(6);
        individuo.add(2);
        individuo.add(3);
        individuo.add(7);
        individuo.add(10);
        individuo.add(9);
        individuo.add(3);
        individuo.add(10);
        individuo.add(11);
        individuo.add(8);
        individuo.add(7);
        individuo.add(10);
        individuo.add(11);
        individuo.add(6);
        individuo.add(5);
        individuo.add(6);
        individuo.add(2);
        individuo.add(4);
        individuo.add(7);
        individuo.add(6);
        individuo.add(3);
        individuo.add(4);
        individuo.add(10);
        individuo.add(8);
        individuo.add(3);
        individuo.add(1);
        individuo.add(3);
        individuo.add(4);
        individuo.add(6);
        individuo.add(1);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(21).setSolucao(S);
        individuo.clear();
        
        individuo.add(1);
        individuo.add(5);
        individuo.add(3);
        individuo.add(8);
        individuo.add(6);
        individuo.add(1);
        individuo.add(2);
        individuo.add(10);
        individuo.add(8);
        individuo.add(6);
        individuo.add(1);
        individuo.add(4);
        individuo.add(5);
        individuo.add(11);
        individuo.add(6);
        individuo.add(7);
        individuo.add(8);
        individuo.add(4);
        individuo.add(2);
        individuo.add(9);
        individuo.add(3);
        individuo.add(3);
        individuo.add(4);
        individuo.add(1);
        individuo.add(8);
        individuo.add(6);
        individuo.add(1);
        individuo.add(7);
        individuo.add(8);
        individuo.add(1);
        individuo.add(10);
        individuo.add(8);
        individuo.add(3);
        individuo.add(2);
        individuo.add(1);
        individuo.add(3);
        individuo.add(5);
        individuo.add(6);
        individuo.add(4);
        individuo.add(2);
        individuo.add(7);
        individuo.add(6);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(22).setSolucao(S);
        individuo.clear();
        
        individuo.add(9);
        individuo.add(2);
        individuo.add(5);
        individuo.add(6);
        individuo.add(10);
        individuo.add(8);
        individuo.add(7);
        individuo.add(4);
        individuo.add(3);
        individuo.add(1);
        individuo.add(11);
        individuo.add(7);
        individuo.add(10);
        individuo.add(7);
        individuo.add(9);
        individuo.add(8);
        individuo.add(1);
        individuo.add(11);
        individuo.add(6);
        individuo.add(1);
        individuo.add(3);
        individuo.add(2);
        individuo.add(8);
        individuo.add(3);
        individuo.add(6);
        individuo.add(10);
        individuo.add(5);
        individuo.add(10);
        individuo.add(6);
        individuo.add(9);
        individuo.add(3);
        individuo.add(8);
        individuo.add(1);
        individuo.add(10);
        individuo.add(5);
        individuo.add(9);
        individuo.add(6);
        individuo.add(8);
        individuo.add(4);
        individuo.add(10);
        individuo.add(2);
        individuo.add(6);
        individuo.add(3);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(23).setSolucao(S);
        individuo.clear();

        individuo.add(2);
        individuo.add(1);
        individuo.add(8);
        individuo.add(6);
        individuo.add(1);
        individuo.add(2);
        individuo.add(8);
        individuo.add(3);
        individuo.add(5);
        individuo.add(10);
        individuo.add(3);
        individuo.add(4);
        individuo.add(6);
        individuo.add(5);
        individuo.add(1);
        individuo.add(4);
        individuo.add(10);
        individuo.add(3);
        individuo.add(6);
        individuo.add(10);
        individuo.add(10);
        individuo.add(11);
        individuo.add(8);
        individuo.add(7);
        individuo.add(11);
        individuo.add(9);
        individuo.add(7);
        individuo.add(6);
        individuo.add(7);
        individuo.add(10);
        individuo.add(11);
        individuo.add(6);
        individuo.add(2);
        individuo.add(1);
        individuo.add(9);
        individuo.add(10);
        individuo.add(7);
        individuo.add(2);
        individuo.add(10);
        individuo.add(8);
        individuo.add(3);
        individuo.add(1);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(24).setSolucao(S);
        individuo.clear();
        
        individuo.add(3);
        individuo.add(5);
        individuo.add(10);
        individuo.add(4);
        individuo.add(1);
        individuo.add(7);
        individuo.add(7);
        individuo.add(8);
        individuo.add(1);
        individuo.add(8);
        individuo.add(3);
        individuo.add(2);
        individuo.add(9);
        individuo.add(2);
        individuo.add(8);
        individuo.add(6);
        individuo.add(4);
        individuo.add(10);
        individuo.add(1);
        individuo.add(3);
        individuo.add(2);
        individuo.add(1);
        individuo.add(8);
        individuo.add(9);
        individuo.add(3);
        individuo.add(5);
        individuo.add(6);
        individuo.add(2);
        individuo.add(6);
        individuo.add(10);
        individuo.add(4);
        individuo.add(7);
        individuo.add(10);
        individuo.add(3);
        individuo.add(6);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(25).setSolucao(S);
        individuo.clear();
        
        individuo.add(7);
        individuo.add(8);
        individuo.add(1);
        individuo.add(8);
        individuo.add(3);
        individuo.add(2);
        individuo.add(5);
        individuo.add(9);
        individuo.add(10);
        individuo.add(3);
        individuo.add(4);
        individuo.add(1);
        individuo.add(7);
        individuo.add(6);
        individuo.add(3);
        individuo.add(1);
        individuo.add(4);
        individuo.add(2);
        individuo.add(9);
        individuo.add(3);
        individuo.add(8);
        individuo.add(1);
        individuo.add(9);
        individuo.add(11);
        individuo.add(5);
        individuo.add(9);
        individuo.add(1);
        individuo.add(4);
        individuo.add(5);
        individuo.add(11);
        individuo.add(6);
        individuo.add(9);
        individuo.add(7);
        individuo.add(8);
        individuo.add(10);
        individuo.add(7);
        individuo.add(10);
        individuo.add(6);
        individuo.add(4);
        individuo.add(6);
        individuo.add(10);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(26).setSolucao(S);
        individuo.clear();

        individuo.add(4);
        individuo.add(7);
        individuo.add(3);
        individuo.add(10);
        individuo.add(3);
        individuo.add(6);
        individuo.add(5);
        individuo.add(9);
        individuo.add(1);
        individuo.add(4);
        individuo.add(5);
        individuo.add(6);
        individuo.add(9);
        individuo.add(8);
        individuo.add(10);
        individuo.add(5);
        individuo.add(7);
        individuo.add(10);
        individuo.add(8);
        individuo.add(1);
        individuo.add(3);
        individuo.add(1);
        individuo.add(5);
        individuo.add(3);
        individuo.add(10);
        individuo.add(3);
        individuo.add(4);
        individuo.add(3);
        individuo.add(1);
        individuo.add(7);
        individuo.add(6);
        individuo.add(1);
        individuo.add(4);
        individuo.add(3);
        individuo.add(8);
        individuo.add(1);
        individuo.add(9);
        individuo.add(7);
        individuo.add(11);
        individuo.add(10);
        individuo.add(2);
        individuo.add(6);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(27).setSolucao(S);
        individuo.clear();

        individuo.add(1);
        individuo.add(5);
        individuo.add(3);
        individuo.add(8);
        individuo.add(6);
        individuo.add(9);
        individuo.add(7);
        individuo.add(1);
        individuo.add(8);
        individuo.add(11);
        individuo.add(1);
        individuo.add(2);
        individuo.add(3);
        individuo.add(4);
        individuo.add(1);
        individuo.add(6);
        individuo.add(3);
        individuo.add(10);
        individuo.add(11);
        individuo.add(7);
        individuo.add(6);
        individuo.add(8);
        individuo.add(6);
        individuo.add(2);
        individuo.add(10);
        individuo.add(2);
        individuo.add(6);
        individuo.add(9);
        individuo.add(11);
        individuo.add(8);
        individuo.add(6);
        individuo.add(7);
        individuo.add(1);
        individuo.add(10);
        individuo.add(1);
        individuo.add(5);
        individuo.add(9);
        individuo.add(2);
        individuo.add(5);
        individuo.add(10);
        individuo.add(8);
        individuo.add(3);
        individuo.add(7);
        individuo.add(1);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(28).setSolucao(S);
        individuo.clear();

        individuo.add(5);
        individuo.add(9);
        individuo.add(6);
        individuo.add(8);
        individuo.add(2);
        individuo.add(8);
        individuo.add(9);
        individuo.add(4);
        individuo.add(8);
        individuo.add(1);
        individuo.add(11);
        individuo.add(7);
        individuo.add(5);
        individuo.add(7);
        individuo.add(2);
        individuo.add(6);
        individuo.add(4);
        individuo.add(1);
        individuo.add(7);
        individuo.add(8);
        individuo.add(6);
        individuo.add(1);
        individuo.add(3);
        individuo.add(5);
        individuo.add(9);
        individuo.add(10);
        individuo.add(9);
        individuo.add(3);
        individuo.add(6);
        individuo.add(2);
        individuo.add(4);
        individuo.add(6);
        individuo.add(8);
        individuo.add(1);
        individuo.add(4);
        individuo.add(10);
        individuo.add(3);
        individuo.add(6);
        individuo.add(10);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(29).setSolucao(S);
        individuo.clear();

        individuo.add(6);
        individuo.add(9);
        individuo.add(10);
        individuo.add(8);
        individuo.add(7);
        individuo.add(2);
        individuo.add(1);
        individuo.add(1);
        individuo.add(5);
        individuo.add(1);
        individuo.add(8);
        individuo.add(3);
        individuo.add(6);
        individuo.add(5);
        individuo.add(7);
        individuo.add(1);
        individuo.add(3);
        individuo.add(2);
        individuo.add(6);
        individuo.add(9);
        individuo.add(4);
        individuo.add(8);
        individuo.add(3);
        individuo.add(4);
        individuo.add(10);
        individuo.add(8);
        individuo.add(1);
        individuo.add(3);
        individuo.add(10);
        individuo.add(8);
        individuo.add(1);
        individuo.add(5);
        individuo.add(1);
        individuo.add(7);
        individuo.add(2);
        individuo.add(3);
        individuo.add(10);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(30).setSolucao(S);
        individuo.clear();

        individuo.add(2);
        individuo.add(1);
        individuo.add(8);
        individuo.add(5);
        individuo.add(7);
        individuo.add(6);
        individuo.add(7);
        individuo.add(10);
        individuo.add(6);
        individuo.add(3);
        individuo.add(4);
        individuo.add(10);
        individuo.add(1);
        individuo.add(2);
        individuo.add(7);
        individuo.add(3);
        individuo.add(8);
        individuo.add(1);
        individuo.add(9);
        individuo.add(11);
        individuo.add(5);
        individuo.add(9);
        individuo.add(8);
        individuo.add(1);
        individuo.add(4);
        individuo.add(7);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        individuo.add(9);
        individuo.add(6);
        individuo.add(2);
        individuo.add(10);
        individuo.add(2);
        individuo.add(6);
        individuo.add(9);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(31).setSolucao(S);
        individuo.clear();

        individuo.add(3);
        individuo.add(2);
        individuo.add(6);
        individuo.add(8);
        individuo.add(3);
        individuo.add(10);
        individuo.add(8);
        individuo.add(1);
        individuo.add(9);
        individuo.add(11);
        individuo.add(5);
        individuo.add(9);
        individuo.add(8);
        individuo.add(6);
        individuo.add(1);
        individuo.add(4);
        individuo.add(5);
        individuo.add(9);
        individuo.add(5);
        individuo.add(9);
        individuo.add(10);
        individuo.add(4);
        individuo.add(3);
        individuo.add(6);
        individuo.add(4);
        individuo.add(2);
        individuo.add(6);
        individuo.add(10);
        individuo.add(11);
        individuo.add(8);
        individuo.add(6);
        individuo.add(9);
        individuo.add(3);
        individuo.add(7);
        individuo.add(4);
        individuo.add(8);
        individuo.add(10);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(32).setSolucao(S);
        individuo.clear();

        individuo.add(9);
        individuo.add(11);
        individuo.add(5);
        individuo.add(1);
        individuo.add(9);
        individuo.add(2);
        individuo.add(10);
        individuo.add(8);
        individuo.add(6);
        individuo.add(4);
        individuo.add(3);
        individuo.add(10);
        individuo.add(2);
        individuo.add(5);
        individuo.add(2);
        individuo.add(5);
        individuo.add(7);
        individuo.add(1);
        individuo.add(8);
        individuo.add(2);
        individuo.add(1);
        individuo.add(9);
        individuo.add(10);
        individuo.add(3);
        individuo.add(5);
        individuo.add(4);
        individuo.add(2);
        individuo.add(7);
        individuo.add(6);
        individuo.add(10);
        individuo.add(7);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(58).setSolucao(S);
        individuo.clear();

        individuo.add(10);
        individuo.add(8);
        individuo.add(1);
        individuo.add(11);
        individuo.add(9);
        individuo.add(6);
        individuo.add(11);
        individuo.add(8);
        individuo.add(1);
        individuo.add(5);
        individuo.add(9);
        individuo.add(10);
        individuo.add(3);
        individuo.add(4);
        individuo.add(1);
        individuo.add(3);
        individuo.add(6);
        individuo.add(1);
        individuo.add(5);
        individuo.add(4);
        individuo.add(7);
        individuo.add(5);
        individuo.add(10);
        individuo.add(6);
        individuo.add(1);
        individuo.add(10);
        individuo.add(9);
        individuo.add(6);
        individuo.add(2);
        individuo.add(7);
        individuo.add(10);
        individuo.add(9);
        individuo.add(3);
        individuo.add(7);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(33).setSolucao(S);
        individuo.clear();

        individuo.add(2);
        individuo.add(5);
        individuo.add(10);
        individuo.add(7);
        individuo.add(1);
        individuo.add(7);
        individuo.add(8);
        individuo.add(1);
        individuo.add(3);
        individuo.add(9);
        individuo.add(2);
        individuo.add(6);
        individuo.add(4);
        individuo.add(2);
        individuo.add(6);
        individuo.add(10);
        individuo.add(11);
        individuo.add(7);
        individuo.add(11);
        individuo.add(4);
        individuo.add(8);
        individuo.add(6);
        individuo.add(1);
        individuo.add(3);
        individuo.add(10);
        individuo.add(9);
        individuo.add(10);
        individuo.add(9);
        individuo.add(5);
        individuo.add(11);
        individuo.add(8);
        individuo.add(3);
        individuo.add(7);
        individuo.add(10);
        individuo.add(4);
        individuo.add(10);
        individuo.add(3);
        individuo.add(6);
        individuo.add(10);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(34).setSolucao(S);
        individuo.clear();

        individuo.add(3);
        individuo.add(10);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        individuo.add(3);
        individuo.add(8);
        individuo.add(10);
        individuo.add(9);
        individuo.add(2);
        individuo.add(5);
        individuo.add(9);
        individuo.add(6);
        individuo.add(1);
        individuo.add(3);
        individuo.add(8);
        individuo.add(4);
        individuo.add(7);
        individuo.add(2);
        individuo.add(3);
        individuo.add(4);
        individuo.add(10);
        individuo.add(1);
        individuo.add(8);
        individuo.add(1);
        individuo.add(11);
        individuo.add(8);
        individuo.add(6);
        individuo.add(1);
        individuo.add(6);
        individuo.add(8);
        individuo.add(4);
        individuo.add(3);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(35).setSolucao(S);
        individuo.clear();

        individuo.add(6);
        individuo.add(9);
        individuo.add(4);
        individuo.add(8);
        individuo.add(2);
        individuo.add(10);
        individuo.add(1);
        individuo.add(6);
        individuo.add(5);
        individuo.add(9);
        individuo.add(10);
        individuo.add(4);
        individuo.add(10);
        individuo.add(6);
        individuo.add(1);
        individuo.add(3);
        individuo.add(5);
        individuo.add(4);
        individuo.add(7);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        individuo.add(3);
        individuo.add(6);
        individuo.add(5);
        individuo.add(9);
        individuo.add(8);
        individuo.add(4);
        individuo.add(1);
        individuo.add(9);
        individuo.add(10);
        individuo.add(2);
        individuo.add(7);
        individuo.add(10);
        individuo.add(1);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(36).setSolucao(S);
        individuo.clear();

        individuo.add(5);
        individuo.add(9);
        individuo.add(6);
        individuo.add(8);
        individuo.add(4);
        individuo.add(7);
        individuo.add(5);
        individuo.add(10);
        individuo.add(1);
        individuo.add(5);
        individuo.add(3);
        individuo.add(9);
        individuo.add(6);
        individuo.add(10);
        individuo.add(9);
        individuo.add(7);
        individuo.add(10);
        individuo.add(2);
        individuo.add(6);
        individuo.add(5);
        individuo.add(8);
        individuo.add(9);
        individuo.add(10);
        individuo.add(1);
        individuo.add(3);
        individuo.add(4);
        individuo.add(1);
        individuo.add(7);
        individuo.add(3);
        individuo.add(3);
        individuo.add(6);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(37).setSolucao(S);
        individuo.clear();

        individuo.add(3);
        individuo.add(6);
        individuo.add(5);
        individuo.add(1);
        individuo.add(7);
        individuo.add(2);
        individuo.add(5);
        individuo.add(9);
        individuo.add(6);
        individuo.add(9);
        individuo.add(8);
        individuo.add(4);
        individuo.add(10);
        individuo.add(2);
        individuo.add(3);
        individuo.add(10);
        individuo.add(6);
        individuo.add(1);
        individuo.add(7);
        individuo.add(10);
        individuo.add(6);
        individuo.add(4);
        individuo.add(6);
        individuo.add(10);
        individuo.add(11);
        individuo.add(7);
        individuo.add(10);
        individuo.add(11);
        individuo.add(8);
        individuo.add(1);
        individuo.add(7);
        individuo.add(6);
        individuo.add(1);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(38).setSolucao(S);
        individuo.clear();

        individuo.add(2);
        individuo.add(1);
        individuo.add(8);
        individuo.add(6);
        individuo.add(1);
        individuo.add(5);
        individuo.add(6);
        individuo.add(10);
        individuo.add(8);
        individuo.add(1);
        individuo.add(3);
        individuo.add(4);
        individuo.add(3);
        individuo.add(2);
        individuo.add(8);
        individuo.add(6);
        individuo.add(3);
        individuo.add(4);
        individuo.add(10);
        individuo.add(7);
        individuo.add(5);
        individuo.add(10);
        individuo.add(1);
        individuo.add(10);
        individuo.add(8);
        individuo.add(8);
        individuo.add(1);
        individuo.add(9);
        individuo.add(7);
        individuo.add(11);
        individuo.add(10);
        individuo.add(2);
        individuo.add(6);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(39).setSolucao(S);
        individuo.clear();

        individuo.add(3);
        individuo.add(10);
        individuo.add(6);
        individuo.add(3);
        individuo.add(4);
        individuo.add(10);
        individuo.add(6);
        individuo.add(8);
        individuo.add(6);
        individuo.add(4);
        individuo.add(10);
        individuo.add(3);
        individuo.add(6);
        individuo.add(10);
        individuo.add(7);
        individuo.add(10);
        individuo.add(10);
        individuo.add(8);
        individuo.add(1);
        individuo.add(11);
        individuo.add(6);
        individuo.add(5);
        individuo.add(10);
        individuo.add(1);
        individuo.add(7);
        individuo.add(2);
        individuo.add(1);
        individuo.add(5);
        individuo.add(10);
        individuo.add(7);
        individuo.add(8);
        individuo.add(7);
        individuo.add(8);
        individuo.add(2);
        individuo.add(1);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(40).setSolucao(S);
        individuo.clear();

        individuo.add(4);
        individuo.add(10);
        individuo.add(6);
        individuo.add(4);
        individuo.add(3);
        individuo.add(10);
        individuo.add(9);
        individuo.add(2);
        individuo.add(6);
        individuo.add(4);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        individuo.add(5);
        individuo.add(2);
        individuo.add(3);
        individuo.add(9);
        individuo.add(3);
        individuo.add(4);
        individuo.add(10);
        individuo.add(6);
        individuo.add(10);
        individuo.add(4);
        individuo.add(1);
        individuo.add(7);
        individuo.add(3);
        individuo.add(7);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(41).setSolucao(S);
        individuo.clear();

        individuo.add(7);
        individuo.add(8);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        individuo.add(7);
        individuo.add(10);
        individuo.add(2);
        individuo.add(6);
        individuo.add(11);
        individuo.add(6);
        individuo.add(9);
        individuo.add(4);
        individuo.add(8);
        individuo.add(1);
        individuo.add(6);
        individuo.add(7);
        individuo.add(10);
        individuo.add(2);
        individuo.add(5);
        individuo.add(1);
        individuo.add(10);
        individuo.add(7);
        individuo.add(10);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        individuo.add(6);
        individuo.add(8);
        individuo.add(4);
        individuo.add(1);
        individuo.add(9);
        individuo.add(5);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(42).setSolucao(S);
        individuo.clear();

        individuo.add(3);
        individuo.add(6);
        individuo.add(5);
        individuo.add(1);
        individuo.add(7);
        individuo.add(10);
        individuo.add(2);
        individuo.add(6);
        individuo.add(7);
        individuo.add(8);
        individuo.add(2);
        individuo.add(1);
        individuo.add(9);
        individuo.add(10);
        individuo.add(7);
        individuo.add(2);
        individuo.add(10);
        individuo.add(1);
        individuo.add(2);
        individuo.add(5);
        individuo.add(1);
        individuo.add(6);
        individuo.add(2);
        individuo.add(10);
        individuo.add(9);
        individuo.add(6);
        individuo.add(1);
        individuo.add(4);
        individuo.add(5);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(43).setSolucao(S);
        individuo.clear();

        individuo.add(9);
        individuo.add(10);
        individuo.add(3);
        individuo.add(4);
        individuo.add(5);
        individuo.add(7);
        individuo.add(10);
        individuo.add(1);
        individuo.add(2);
        individuo.add(1);
        individuo.add(5);
        individuo.add(8);
        individuo.add(1);
        individuo.add(11);
        individuo.add(6);
        individuo.add(10);
        individuo.add(2);
        individuo.add(6);
        individuo.add(10);
        individuo.add(4);
        individuo.add(3);
        individuo.add(2);
        individuo.add(7);
        individuo.add(8);
        individuo.add(3);
        individuo.add(9);
        individuo.add(1);
        individuo.add(10);
        individuo.add(2);
        individuo.add(9);
        individuo.add(8);
        individuo.add(4);
        individuo.add(10);
        individuo.add(6);
        individuo.add(1);
        individuo.add(9);
        individuo.add(7);
        individuo.add(8);
        individuo.add(1);
        individuo.add(6);
        individuo.add(4);
        individuo.add(2);
        individuo.add(11);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(44).setSolucao(S);
        individuo.clear();

        individuo.add(3);
        individuo.add(6);
        individuo.add(5);
        individuo.add(9);
        individuo.add(6);
        individuo.add(1);
        individuo.add(4);
        individuo.add(4);
        individuo.add(2);
        individuo.add(9);
        individuo.add(3);
        individuo.add(10);
        individuo.add(8);
        individuo.add(1);
        individuo.add(5);
        individuo.add(7);
        individuo.add(1);
        individuo.add(6);
        individuo.add(1);
        individuo.add(4);
        individuo.add(2);
        individuo.add(5);
        individuo.add(10);
        individuo.add(9);
        individuo.add(2);
        individuo.add(5);
        individuo.add(7);
        individuo.add(10);
        individuo.add(1);
        individuo.add(3);
        individuo.add(6);
        individuo.add(8);
        individuo.add(9);
        individuo.add(2);
        individuo.add(10);
        individuo.add(2);
        individuo.add(6);
        individuo.add(8);

        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(45).setSolucao(S);
        individuo.clear();
        
        individuo.add(2);
        individuo.add(1);
        individuo.add(5);
        individuo.add(10);
        individuo.add(7);
        individuo.add(8);
        individuo.add(9);
        individuo.add(2);
        individuo.add(6);
        individuo.add(4);
        individuo.add(8);
        individuo.add(3);
        individuo.add(7);
        individuo.add(8);
        individuo.add(2);
        individuo.add(1);
        individuo.add(3);
        individuo.add(4);
        individuo.add(10);
        individuo.add(1);
        individuo.add(3);
        individuo.add(10);
        individuo.add(6);
        individuo.add(3);
        individuo.add(10);
        individuo.add(4);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(46).setSolucao(S);
        individuo.clear();

        individuo.add(3);
        individuo.add(6);
        individuo.add(5);
        individuo.add(1);
        individuo.add(7);
        individuo.add(8);
        individuo.add(1);
        individuo.add(10);
        individuo.add(1);
        individuo.add(2);
        individuo.add(1);
        individuo.add(5);
        individuo.add(10);
        individuo.add(6);
        individuo.add(3);
        individuo.add(10);
        individuo.add(6);
        individuo.add(4);
        individuo.add(3);
        individuo.add(10);
        individuo.add(10);
        individuo.add(11);
        individuo.add(6);
        individuo.add(9);
        individuo.add(3);
        individuo.add(8);
        individuo.add(7);
        individuo.add(10);
        individuo.add(6);
        individuo.add(4);
        individuo.add(10);
        individuo.add(6);
        individuo.add(5);
        individuo.add(7);
        individuo.add(1);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(47).setSolucao(S);
        individuo.clear();

        individuo.add(10);
        individuo.add(11);
        individuo.add(8);
        individuo.add(10);
        individuo.add(4);
        individuo.add(7);
        individuo.add(1);
        individuo.add(3);
        individuo.add(1);
        individuo.add(5);
        individuo.add(10);
        individuo.add(11);
        individuo.add(6);
        individuo.add(10);
        individuo.add(2);
        individuo.add(6);
        individuo.add(7);
        individuo.add(8);
        individuo.add(1);
        individuo.add(5);
        individuo.add(2);
        individuo.add(5);
        individuo.add(6);
        individuo.add(7);
        individuo.add(4);
        individuo.add(1);
        individuo.add(7);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        individuo.add(7);
        individuo.add(5);
        individuo.add(1);
        individuo.add(10);
        individuo.add(6);
        individuo.add(10);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(48).setSolucao(S);
        individuo.clear();

        individuo.add(11);
        individuo.add(8);
        individuo.add(6);
        individuo.add(5);
        individuo.add(1);
        individuo.add(10);
        individuo.add(7);
        individuo.add(1);
        individuo.add(3);
        individuo.add(4);
        individuo.add(1);
        individuo.add(6);
        individuo.add(8);
        individuo.add(6);
        individuo.add(1);
        individuo.add(11);
        individuo.add(6);
        individuo.add(9);
        individuo.add(2);
        individuo.add(10);
        individuo.add(6);
        individuo.add(8);
        individuo.add(3);
        individuo.add(7);
        individuo.add(4);
        individuo.add(10);
        individuo.add(8);
        individuo.add(8);
        individuo.add(1);
        individuo.add(9);
        individuo.add(11);
        individuo.add(5);
        individuo.add(9);
        individuo.add(4);
        individuo.add(1);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(49).setSolucao(S);
        individuo.clear();

        individuo.add(8);
        individuo.add(1);
        individuo.add(3);
        individuo.add(5);
        individuo.add(6);
        individuo.add(2);
        individuo.add(7);
        individuo.add(6);
        individuo.add(4);
        individuo.add(6);
        individuo.add(8);
        individuo.add(6);
        individuo.add(10);
        individuo.add(9);
        individuo.add(7);
        individuo.add(10);
        individuo.add(6);
        individuo.add(8);
        individuo.add(4);
        individuo.add(3);
        individuo.add(10);
        individuo.add(8);
        individuo.add(1);
        individuo.add(7);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        individuo.add(9);
        individuo.add(4);
        individuo.add(3);
        individuo.add(2);
        individuo.add(6);
        individuo.add(8);
        individuo.add(1);
        individuo.add(9);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(50).setSolucao(S);
        individuo.clear();

        individuo.add(10);
        individuo.add(2);
        individuo.add(10);
        individuo.add(3);
        individuo.add(7);
        individuo.add(8);
        individuo.add(9);
        individuo.add(3);
        individuo.add(6);
        individuo.add(10);
        individuo.add(6);
        individuo.add(4);
        individuo.add(2);
        individuo.add(6);
        individuo.add(10);
        individuo.add(9);
        individuo.add(6);
        individuo.add(2);
        individuo.add(3);
        individuo.add(9);
        individuo.add(4);
        individuo.add(10);
        individuo.add(6);
        individuo.add(8);
        individuo.add(4);
        individuo.add(2);
        individuo.add(3);
        individuo.add(10);
        individuo.add(9);
        individuo.add(1);
        individuo.add(6);
        individuo.add(1);
        individuo.add(2);
        individuo.add(10);
        individuo.add(6);
        individuo.add(4);
        individuo.add(6);
        individuo.add(10);
        individuo.add(8);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(51).setSolucao(S);
        individuo.clear();

        individuo.add(8);
        individuo.add(1);
        individuo.add(5);
        individuo.add(2);
        individuo.add(5);
        individuo.add(1);
        individuo.add(10);
        individuo.add(8);
        individuo.add(1);
        individuo.add(3);
        individuo.add(7);
        individuo.add(11);
        individuo.add(7);
        individuo.add(6);
        individuo.add(8);
        individuo.add(6);
        individuo.add(2);
        individuo.add(7);
        individuo.add(9);
        individuo.add(3);
        individuo.add(10);
        individuo.add(7);
        individuo.add(5);
        individuo.add(10);
        individuo.add(1);
        individuo.add(7);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        individuo.add(8);
        individuo.add(1);
        individuo.add(4);
        individuo.add(10);
        individuo.add(3);
        individuo.add(6);
        individuo.add(10);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(52).setSolucao(S);
        individuo.clear();

        individuo.add(11);
        individuo.add(6);
        individuo.add(7);
        individuo.add(5);
        individuo.add(10);
        individuo.add(1);
        individuo.add(5);
        individuo.add(9);
        individuo.add(6);
        individuo.add(4);
        individuo.add(2);
        individuo.add(3);
        individuo.add(7);
        individuo.add(8);
        individuo.add(10);
        individuo.add(9);
        individuo.add(3);
        individuo.add(1);
        individuo.add(9);
        individuo.add(11);
        individuo.add(7);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        individuo.add(11);
        individuo.add(6);
        individuo.add(8);
        individuo.add(9);
        individuo.add(10);
        individuo.add(5);
        individuo.add(7);
        individuo.add(10);
        individuo.add(1);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(53).setSolucao(S);
        individuo.clear();

        individuo.add(3);
        individuo.add(5);
        individuo.add(6);
        individuo.add(2);
        individuo.add(7);
        individuo.add(6);
        individuo.add(4);
        individuo.add(6);
        individuo.add(8);
        individuo.add(9);
        individuo.add(2);
        individuo.add(5);
        individuo.add(1);
        individuo.add(10);
        individuo.add(1);
        individuo.add(5);
        individuo.add(8);
        individuo.add(3);
        individuo.add(4);
        individuo.add(6);
        individuo.add(1);
        individuo.add(11);
        individuo.add(7);
        individuo.add(10);
        individuo.add(11);
        individuo.add(8);
        individuo.add(7);
        individuo.add(9);
        individuo.add(7);
        individuo.add(6);
        individuo.add(1);
        individuo.add(7);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(54).setSolucao(S);
        individuo.clear();

        individuo.add(4);
        individuo.add(2);
        individuo.add(3);
        individuo.add(8);
        individuo.add(9);
        individuo.add(8);
        individuo.add(3);
        individuo.add(1);
        individuo.add(7);
        individuo.add(8);
        individuo.add(1);
        individuo.add(6);
        individuo.add(2);
        individuo.add(4);
        individuo.add(3);
        individuo.add(2);
        individuo.add(5);
        individuo.add(9);
        individuo.add(6);
        individuo.add(1);
        individuo.add(8);
        individuo.add(4);
        individuo.add(8);
        individuo.add(1);
        individuo.add(9);
        individuo.add(11);
        individuo.add(6);
        individuo.add(9);
        individuo.add(10);
        individuo.add(5);
        individuo.add(7);
        individuo.add(8);
        individuo.add(10);
        individuo.add(1);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(55).setSolucao(S);
        individuo.clear();

        individuo.add(6);
        individuo.add(8);
        individuo.add(2);
        individuo.add(8);
        individuo.add(3);
        individuo.add(10);
        individuo.add(6);
        individuo.add(3);
        individuo.add(6);
        individuo.add(5);
        individuo.add(9);
        individuo.add(8);
        individuo.add(4);
        individuo.add(1);
        individuo.add(4);
        individuo.add(7);
        individuo.add(3);
        individuo.add(10);
        individuo.add(8);
        individuo.add(1);
        individuo.add(11);
        individuo.add(9);
        individuo.add(8);
        individuo.add(11);
        individuo.add(10);
        individuo.add(2);
        individuo.add(1);
        individuo.add(6);
        individuo.add(7);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(56).setSolucao(S);
        individuo.clear();

        individuo.add(3);
        individuo.add(10);
        individuo.add(3);
        individuo.add(4);
        individuo.add(3);
        individuo.add(6);
        individuo.add(4);
        individuo.add(1);
        individuo.add(10);
        individuo.add(6);
        individuo.add(3);
        individuo.add(10);
        individuo.add(2);
        individuo.add(6);
        individuo.add(10);
        individuo.add(8);
        individuo.add(1);
        individuo.add(7);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        individuo.add(8);
        individuo.add(1);
        individuo.add(4);
        individuo.add(2);
        individuo.add(9);
        individuo.add(10);
        individuo.add(8);
        individuo.add(3);
        individuo.add(1);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(57).setSolucao(S);
        individuo.clear();

        individuo.add(6);
        individuo.add(8);
        individuo.add(3);
        individuo.add(6);
        individuo.add(9);
        individuo.add(10);
        individuo.add(2);
        individuo.add(5);
        individuo.add(10);
        individuo.add(7);
        individuo.add(1);
        individuo.add(11);
        individuo.add(7);
        individuo.add(11);
        individuo.add(7);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        individuo.add(10);
        individuo.add(2);
        individuo.add(8);
        individuo.add(4);
        individuo.add(1);
        individuo.add(8);
        individuo.add(1);
        individuo.add(9);
        individuo.add(7);
        individuo.add(10);
        individuo.add(2);
        individuo.add(6);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(58).setSolucao(S);
        individuo.clear();
        
//        individuo.add(6);
//        individuo.add(8);
//        individuo.add(3);
//        individuo.add(6);
//        individuo.add(9);
//        individuo.add(10);
//        individuo.add(2);
//        individuo.add(5);
//        individuo.add(10);
//        individuo.add(7);
//        individuo.add(1);
//        individuo.add(11);
//        individuo.add(7);
//        individuo.add(11);
//        individuo.add(7);
//        individuo.add(2);
//        individuo.add(6);
//        individuo.add(1);
//        individuo.add(10);
//        individuo.add(2);
//        individuo.add(8);
//        individuo.add(4);
//        individuo.add(1);
//        individuo.add(8);
//        individuo.add(1);
//        individuo.add(9);
//        individuo.add(7);
//        individuo.add(10);
//        individuo.add(2);
//        individuo.add(6);
        
        individuo.add(7);
        individuo.add(2);
        individuo.add(3);
        individuo.add(2);
        individuo.add(6);
        individuo.add(9);
        individuo.add(4);
        individuo.add(8);
        individuo.add(9);
        individuo.add(3);
        individuo.add(4);
        individuo.add(5);
        individuo.add(10);
        individuo.add(8);
        individuo.add(3);
        individuo.add(7);
        individuo.add(1);
        individuo.add(1);
        individuo.add(5);
        individuo.add(3);
        individuo.add(10);
        individuo.add(6);
        individuo.add(3);
        individuo.add(2);
        individuo.add(10);
        individuo.add(7);
        individuo.add(6);
        individuo.add(1);
        individuo.add(9);
        individuo.add(3);
        individuo.add(1);
        individuo.add(3);
        individuo.add(1);
        individuo.add(2);
        individuo.add(9);
        individuo.add(8);
        individuo.add(4);
        individuo.add(5);
        individuo.add(10);
        individuo.add(2);
        individuo.add(3);
        individuo.add(1);
        individuo.add(6);
        individuo.add(5);
        
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
        Pop.get(59).setSolucao(S);
        individuo.clear();


    }
    
    public static Solucao CarregaUmaSolucao(List<Solucao> Pop,List<Request> listRequests, Map<Integer, List<Request>> Pin,
                                      Map<Integer, List<Request>> Pout, Integer n, Integer Qmax, Set<Integer> K, List<Request> U, List<Request> P,
                                      List<Integer> m, List<List<Integer>> d, List<List<Integer>> c, Integer TimeWindows, Integer currentTime){
        Solucao S = new Solucao();
        List<Integer> individuo = new ArrayList<>();
        
//        individuo.add(7);
//        individuo.add(2);
//        individuo.add(3);
//        individuo.add(2);
//        individuo.add(6);
//        individuo.add(9);
//        individuo.add(4);
//        individuo.add(8);
//        individuo.add(9);
//        individuo.add(3);
//        individuo.add(4);
//        individuo.add(5);
//        individuo.add(10);
//        individuo.add(8);
//        individuo.add(3);
//        individuo.add(7);
//        individuo.add(1);
//        individuo.add(1);
//        individuo.add(5);
//        individuo.add(3);
//        individuo.add(10);
//        individuo.add(6);
//        individuo.add(3);
//        individuo.add(2);
//        individuo.add(10);
//        individuo.add(7);
//        individuo.add(6);
//        individuo.add(1);
//        individuo.add(9);
//        individuo.add(3);
//        individuo.add(1);
//        individuo.add(3);
//        individuo.add(1);
//        individuo.add(2);
//        individuo.add(9);
//        individuo.add(8);
//        individuo.add(4);
//        individuo.add(5);
//        individuo.add(10);
//        individuo.add(2);
//        individuo.add(3);
//        individuo.add(1);
//        individuo.add(6);
//        individuo.add(5);
        //System.out.println("Individuo = " + individuo);
//        individuo.add(11);
//        individuo.add(6);
//        individuo.add(1);
//        individuo.add(5);
//        individuo.add(9);
//        individuo.add(8);
//        individuo.add(10);
//        individuo.add(1);
//        individuo.add(3);
//        individuo.add(4);
//        individuo.add(1);
//        individuo.add(6);
//        individuo.add(9);
//        individuo.add(10);
//        individuo.add(5);
//        individuo.add(6);
//        individuo.add(4);
//        individuo.add(2);
//        individuo.add(7);
//        individuo.add(6);
//        individuo.add(8);
//        individuo.add(2);
//        individuo.add(1);
//        individuo.add(5);
//        individuo.add(8);
//        individuo.add(6);
//        individuo.add(5);
//        individuo.add(8);
//        individuo.add(1);
//        individuo.add(2);
//        individuo.add(7);
//        individuo.add(6);
//        individuo.add(10);
//        individuo.add(1);
//        individuo.add(3);
//        individuo.add(2);
//        individuo.add(5);
//        individuo.add(9);
//        individuo.add(4);
//        individuo.add(10);
//        individuo.add(2);
//        individuo.add(3);
//        individuo.add(6);
//       
//        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
//        Rota rota = new Rota();
//        Set<Rota> conjRotas = new HashSet<>();
//        
//        rota.addVisitacao(0);
//        rota.addVisitacao(11);
//        rota.addVisitacao(6);
//        rota.addVisitacao(0);
//        //conjRotas.add(rota);
//        S.getConjRotas().add(rota);
//        rota.getListaVisitacao().clear();
//        
//        
//        rota.addVisitacao(0);
//        rota.addVisitacao(1);
//        rota.addVisitacao(5);
//        rota.addVisitacao(9);
//        rota.addVisitacao(8);
//        rota.addVisitacao(10);
//        rota.addVisitacao(1);
//        rota.addVisitacao(3);
//        rota.addVisitacao(4);
//        rota.addVisitacao(1);
//        
//        rota.addVisitacao(0);
//        //conjRotas.add(rota);
//        S.getConjRotas().add(rota);
//        rota.getListaVisitacao().clear();
//        
//        
//        rota.addVisitacao(0);
//        rota.addVisitacao(6);
//        rota.addVisitacao(9);
//        rota.addVisitacao(10);
//        rota.addVisitacao(5);
//        rota.addVisitacao(6);
//        rota.addVisitacao(4);
//        rota.addVisitacao(2);
//        rota.addVisitacao(7);
//        rota.addVisitacao(6);
//        rota.addVisitacao(8);
//        rota.addVisitacao(0);
//        S.getConjRotas().add(rota);
//        conjRotas.add(rota);
//        rota.getListaVisitacao().clear();
//        
//        
//        rota.addVisitacao(0);
//        rota.addVisitacao(2);
//        rota.addVisitacao(1);
//        rota.addVisitacao(5);
//        rota.addVisitacao(8);
//        rota.addVisitacao(6);
//        rota.addVisitacao(5);
//        rota.addVisitacao(8);
//        rota.addVisitacao(1);
//        rota.addVisitacao(2);
//        rota.addVisitacao(7);
//        rota.addVisitacao(6);
//        rota.addVisitacao(10);
//        rota.addVisitacao(0);
//        S.getConjRotas().add(rota);
//        conjRotas.add(rota);
//        rota.getListaVisitacao().clear();
//
//        
//        rota.addVisitacao(0);
//        rota.addVisitacao(1);
//        rota.addVisitacao(3);
//        rota.addVisitacao(2);
//        rota.addVisitacao(5);
//        rota.addVisitacao(9);
//        rota.addVisitacao(4);
//        rota.addVisitacao(10);
//        rota.addVisitacao(2);
//        rota.addVisitacao(3);
//        rota.addVisitacao(6);
//        rota.addVisitacao(0);
//        S.getConjRotas().add(rota);
//        conjRotas.add(rota);
//        rota.getListaVisitacao().clear();
//        
////        R.addVisitacao(0);
////            currentTime += d.get(lastNode).get(0);
////            S.getConjRotas().add(R);
//        
//        //S.setConjRotas(conjRotas);
//        
//        System.out.println("Tamanho = " + S.getConjRotas().size());
        
        //List<Solucao> Pop = new ArrayList<>();
				
	individuo.add(7);
        individuo.add(8);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        individuo.add(7);
        individuo.add(10);
        individuo.add(2);
        individuo.add(6);
        individuo.add(11);
        individuo.add(6);
        individuo.add(9);
        individuo.add(4);
        individuo.add(8);
        individuo.add(1);
        individuo.add(6);
        individuo.add(7);
        individuo.add(10);
        individuo.add(2);
        individuo.add(5);
        individuo.add(1);
        individuo.add(10);
        individuo.add(7);
        individuo.add(10);
        individuo.add(2);
        individuo.add(6);
        individuo.add(1);
        individuo.add(6);
        individuo.add(8);
        individuo.add(4);
        individuo.add(1);
        individuo.add(9);
        individuo.add(5);
        
        S.setSolucao(avaliaSolucao(individuo, listRequests, P, K, U, Pin, Pout, d, c, n, Qmax, TimeWindows));
               
        
        return S;
    }

    
}
